title: RanViewer
description: RanViewer home page
theme: just-the-docs

url: https://johansolhed.github.io/RanViewer

#baseurl: "/RanViewer"

#logo: "/celltower.png"
#logo: "/assets/images/celltower.png"
logo: "/assets/images/Icon-29x29@3x.png"
favicon_ico: "/assets/images/Icon-29x29@2x.png"

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/johansolhed/RanViewer
